---
name: App Update Template
about: Report an update to an existing app
title: ''
labels: App Update
assignees: ''

---


Replace each second line your own text. 


**The official name of the app**
What's the full official name of the app? 

**Is there a supported version available on a stable release channel?**
Yes or No

**Proposed New App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here. 


**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 



